version: '3.8'

networks:

  inception_network:
    driver: bridge

volumes:

  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME_DIR}/data/mariadb"
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME_DIR}/data/wordpress"

services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - '443:443'
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always
