#!/bin/sh

MYSQL_SETUP_DONE_INDICATOR=/var/lib/mysql/.setupdone

service mysql start

if [ ! -e $MYSQL_SETUP_DONE_INDICATOR ]; then 
	mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE";
	mysql -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'";
	mysql -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%'";
	mysql -e "FLUSH PRIVILEGES";
	mysql -e "ALTER USER '$MYSQL_ROOT'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD'";

	mysql $MYSQL_DATABASE -u $MYSQL_ROOT -p $MYSQL_ROOT_PASSWORD
	mysqladmin -u $MYSQL_ROOT -p $MYSQL_ROOT_PASSWORD shutdown

	touch $MYSQL_SETUP_DONE_INDICATOR
fi

exec mysqld_safe
